/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/project/route'
import { Route as CommitteeRouteRouteImport } from './routes/committee/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as CommitteeIndexRouteImport } from './routes/committee/index'
import { Route as ProjectMembersIndexRouteImport } from './routes/project/members/index'
import { Route as ProjectFormsIndexRouteImport } from './routes/project/forms/index'
import { Route as ProjectAnnouncementsIndexRouteImport } from './routes/project/announcements/index'
import { Route as CommitteeNoticeIndexRouteImport } from './routes/committee/notice/index'
import { Route as CommitteeMembersIndexRouteImport } from './routes/committee/members/index'
import { Route as CommitteeMastersheetIndexRouteImport } from './routes/committee/mastersheet/index'
import { Route as CommitteeFormsIndexRouteImport } from './routes/committee/forms/index'
import { Route as CommitteeAnnouncementsIndexRouteImport } from './routes/committee/announcements/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DevUiComponentsIndexRouteImport } from './routes/dev/ui/components/index'
import { Route as AuthRegisterVerifyIndexRouteImport } from './routes/auth/register/verify/index'
import { Route as AuthRegisterSetupIndexRouteImport } from './routes/auth/register/setup/index'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRouteRoute = CommitteeRouteRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const CommitteeIndexRoute = CommitteeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const ProjectMembersIndexRoute = ProjectMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectFormsIndexRoute = ProjectFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectAnnouncementsIndexRoute =
  ProjectAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => ProjectRouteRoute,
  } as any)
const CommitteeNoticeIndexRoute = CommitteeNoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const CommitteeMembersIndexRoute = CommitteeMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const CommitteeMastersheetIndexRoute =
  CommitteeMastersheetIndexRouteImport.update({
    id: '/mastersheet/',
    path: '/mastersheet/',
    getParentRoute: () => CommitteeRouteRoute,
  } as any)
const CommitteeFormsIndexRoute = CommitteeFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const CommitteeAnnouncementsIndexRoute =
  CommitteeAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => CommitteeRouteRoute,
  } as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DevUiComponentsIndexRoute = DevUiComponentsIndexRouteImport.update({
  id: '/dev/ui/components/',
  path: '/dev/ui/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterVerifyIndexRoute = AuthRegisterVerifyIndexRouteImport.update({
  id: '/register/verify/',
  path: '/register/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterSetupIndexRoute = AuthRegisterSetupIndexRouteImport.update({
  id: '/register/setup/',
  path: '/register/setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeRouteRouteWithChildren
  '/project': typeof ProjectRouteRouteWithChildren
  '/committee/': typeof CommitteeIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/search': typeof SearchIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/committee/announcements': typeof CommitteeAnnouncementsIndexRoute
  '/committee/forms': typeof CommitteeFormsIndexRoute
  '/committee/mastersheet': typeof CommitteeMastersheetIndexRoute
  '/committee/members': typeof CommitteeMembersIndexRoute
  '/committee/notice': typeof CommitteeNoticeIndexRoute
  '/project/announcements': typeof ProjectAnnouncementsIndexRoute
  '/project/forms': typeof ProjectFormsIndexRoute
  '/project/members': typeof ProjectMembersIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeIndexRoute
  '/project': typeof ProjectIndexRoute
  '/search': typeof SearchIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/committee/announcements': typeof CommitteeAnnouncementsIndexRoute
  '/committee/forms': typeof CommitteeFormsIndexRoute
  '/committee/mastersheet': typeof CommitteeMastersheetIndexRoute
  '/committee/members': typeof CommitteeMembersIndexRoute
  '/committee/notice': typeof CommitteeNoticeIndexRoute
  '/project/announcements': typeof ProjectAnnouncementsIndexRoute
  '/project/forms': typeof ProjectFormsIndexRoute
  '/project/members': typeof ProjectMembersIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeRouteRouteWithChildren
  '/project': typeof ProjectRouteRouteWithChildren
  '/committee/': typeof CommitteeIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/search/': typeof SearchIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/committee/announcements/': typeof CommitteeAnnouncementsIndexRoute
  '/committee/forms/': typeof CommitteeFormsIndexRoute
  '/committee/mastersheet/': typeof CommitteeMastersheetIndexRoute
  '/committee/members/': typeof CommitteeMembersIndexRoute
  '/committee/notice/': typeof CommitteeNoticeIndexRoute
  '/project/announcements/': typeof ProjectAnnouncementsIndexRoute
  '/project/forms/': typeof ProjectFormsIndexRoute
  '/project/members/': typeof ProjectMembersIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/committee'
    | '/project'
    | '/committee/'
    | '/project/'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/committee/announcements'
    | '/committee/forms'
    | '/committee/mastersheet'
    | '/committee/members'
    | '/committee/notice'
    | '/project/announcements'
    | '/project/forms'
    | '/project/members'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/dev/ui/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/committee'
    | '/project'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/committee/announcements'
    | '/committee/forms'
    | '/committee/mastersheet'
    | '/committee/members'
    | '/committee/notice'
    | '/project/announcements'
    | '/project/forms'
    | '/project/members'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/dev/ui/components'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/committee'
    | '/project'
    | '/committee/'
    | '/project/'
    | '/search/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/committee/announcements/'
    | '/committee/forms/'
    | '/committee/mastersheet/'
    | '/committee/members/'
    | '/committee/notice/'
    | '/project/announcements/'
    | '/project/forms/'
    | '/project/members/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/dev/ui/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CommitteeRouteRoute: typeof CommitteeRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  SearchIndexRoute: typeof SearchIndexRoute
  DevUiComponentsIndexRoute: typeof DevUiComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/committee/': {
      id: '/committee/'
      path: '/'
      fullPath: '/committee/'
      preLoaderRoute: typeof CommitteeIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/project/members/': {
      id: '/project/members/'
      path: '/members'
      fullPath: '/project/members'
      preLoaderRoute: typeof ProjectMembersIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/forms/': {
      id: '/project/forms/'
      path: '/forms'
      fullPath: '/project/forms'
      preLoaderRoute: typeof ProjectFormsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/announcements/': {
      id: '/project/announcements/'
      path: '/announcements'
      fullPath: '/project/announcements'
      preLoaderRoute: typeof ProjectAnnouncementsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/committee/notice/': {
      id: '/committee/notice/'
      path: '/notice'
      fullPath: '/committee/notice'
      preLoaderRoute: typeof CommitteeNoticeIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/committee/members/': {
      id: '/committee/members/'
      path: '/members'
      fullPath: '/committee/members'
      preLoaderRoute: typeof CommitteeMembersIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/committee/mastersheet/': {
      id: '/committee/mastersheet/'
      path: '/mastersheet'
      fullPath: '/committee/mastersheet'
      preLoaderRoute: typeof CommitteeMastersheetIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/committee/forms/': {
      id: '/committee/forms/'
      path: '/forms'
      fullPath: '/committee/forms'
      preLoaderRoute: typeof CommitteeFormsIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/committee/announcements/': {
      id: '/committee/announcements/'
      path: '/announcements'
      fullPath: '/committee/announcements'
      preLoaderRoute: typeof CommitteeAnnouncementsIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dev/ui/components/': {
      id: '/dev/ui/components/'
      path: '/dev/ui/components'
      fullPath: '/dev/ui/components'
      preLoaderRoute: typeof DevUiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/verify/': {
      id: '/auth/register/verify/'
      path: '/register/verify'
      fullPath: '/auth/register/verify'
      preLoaderRoute: typeof AuthRegisterVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/setup/': {
      id: '/auth/register/setup/'
      path: '/register/setup'
      fullPath: '/auth/register/setup'
      preLoaderRoute: typeof AuthRegisterSetupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthRegisterSetupIndexRoute: typeof AuthRegisterSetupIndexRoute
  AuthRegisterVerifyIndexRoute: typeof AuthRegisterVerifyIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthRegisterSetupIndexRoute: AuthRegisterSetupIndexRoute,
  AuthRegisterVerifyIndexRoute: AuthRegisterVerifyIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CommitteeRouteRouteChildren {
  CommitteeIndexRoute: typeof CommitteeIndexRoute
  CommitteeAnnouncementsIndexRoute: typeof CommitteeAnnouncementsIndexRoute
  CommitteeFormsIndexRoute: typeof CommitteeFormsIndexRoute
  CommitteeMastersheetIndexRoute: typeof CommitteeMastersheetIndexRoute
  CommitteeMembersIndexRoute: typeof CommitteeMembersIndexRoute
  CommitteeNoticeIndexRoute: typeof CommitteeNoticeIndexRoute
}

const CommitteeRouteRouteChildren: CommitteeRouteRouteChildren = {
  CommitteeIndexRoute: CommitteeIndexRoute,
  CommitteeAnnouncementsIndexRoute: CommitteeAnnouncementsIndexRoute,
  CommitteeFormsIndexRoute: CommitteeFormsIndexRoute,
  CommitteeMastersheetIndexRoute: CommitteeMastersheetIndexRoute,
  CommitteeMembersIndexRoute: CommitteeMembersIndexRoute,
  CommitteeNoticeIndexRoute: CommitteeNoticeIndexRoute,
}

const CommitteeRouteRouteWithChildren = CommitteeRouteRoute._addFileChildren(
  CommitteeRouteRouteChildren,
)

interface ProjectRouteRouteChildren {
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectAnnouncementsIndexRoute: typeof ProjectAnnouncementsIndexRoute
  ProjectFormsIndexRoute: typeof ProjectFormsIndexRoute
  ProjectMembersIndexRoute: typeof ProjectMembersIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectAnnouncementsIndexRoute: ProjectAnnouncementsIndexRoute,
  ProjectFormsIndexRoute: ProjectFormsIndexRoute,
  ProjectMembersIndexRoute: ProjectMembersIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CommitteeRouteRoute: CommitteeRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  SearchIndexRoute: SearchIndexRoute,
  DevUiComponentsIndexRoute: DevUiComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
