/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DevUiComponentsIndexRouteImport } from './routes/dev/ui/components/index'
import { Route as AuthRegisterVerifyIndexRouteImport } from './routes/auth/register/verify/index'
import { Route as AuthRegisterSetupIndexRouteImport } from './routes/auth/register/setup/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DevUiComponentsIndexRoute = DevUiComponentsIndexRouteImport.update({
  id: '/dev/ui/components/',
  path: '/dev/ui/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterVerifyIndexRoute = AuthRegisterVerifyIndexRouteImport.update({
  id: '/register/verify/',
  path: '/register/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterSetupIndexRoute = AuthRegisterSetupIndexRouteImport.update({
  id: '/register/setup/',
  path: '/register/setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/search': typeof SearchIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/search': typeof SearchIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/search/': typeof SearchIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/dev/ui/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/dev/ui/components'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/search/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/dev/ui/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SearchIndexRoute: typeof SearchIndexRoute
  DevUiComponentsIndexRoute: typeof DevUiComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dev/ui/components/': {
      id: '/dev/ui/components/'
      path: '/dev/ui/components'
      fullPath: '/dev/ui/components'
      preLoaderRoute: typeof DevUiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/verify/': {
      id: '/auth/register/verify/'
      path: '/register/verify'
      fullPath: '/auth/register/verify'
      preLoaderRoute: typeof AuthRegisterVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/setup/': {
      id: '/auth/register/setup/'
      path: '/register/setup'
      fullPath: '/auth/register/setup'
      preLoaderRoute: typeof AuthRegisterSetupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthRegisterSetupIndexRoute: typeof AuthRegisterSetupIndexRoute
  AuthRegisterVerifyIndexRoute: typeof AuthRegisterVerifyIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthRegisterSetupIndexRoute: AuthRegisterSetupIndexRoute,
  AuthRegisterVerifyIndexRoute: AuthRegisterVerifyIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SearchIndexRoute: SearchIndexRoute,
  DevUiComponentsIndexRoute: DevUiComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
